export default {
  chat: "icon-chat",
  empty: "icon-empty",
  arrowDown: "icon-arrow_down",
  arrowUp: "icon-arrow_up",
  weixin: "icon-weixin-copy",
  email: "icon-email",
  github: "icon-github-fill",
  qq: "icon-QQ-circle-fill",
  blog: "icon-blog",
  code: "icon-code",
  about: "icon-about",
  info: "icon-info",
  warn: "icon-warnfill",
  home: "icon-home",
  success: "icon-success-fill",
  close: "icon-close",
  error: "icon-error-fill",
};